import mongoose, { Document, Schema, Types } from "mongoose";
import { LeagueType, LeagueStatus, RankingMode, LineupRole } from "./enums.js";

export interface ILeague extends Document {
  name: string;
  type: LeagueType;
  createdBy?: Types.ObjectId;
  isOfficial: boolean;
  championshipId: Types.ObjectId;
  rankingMode: RankingMode;
  rosterSize: number;
  startersPerGameweek: number;
  initialBudget: number;
  marketEnabled: boolean;
  status: LeagueStatus;
  entryFee?: number;
  prize1st?: string;
  prize2nd?: string;
  prize3rd?: string;
  inviteCode?: string;
  createdAt: Date;
  updatedAt: Date;
}

const LeagueSchema = new Schema<ILeague>(
  {
    name: { type: String, required: true, trim: true },
    type: {
      type: String,
      enum: Object.values(LeagueType),
      required: true,
    },
    createdBy: { type: Schema.Types.ObjectId, ref: "User" },
    isOfficial: { type: Boolean, default: false },
    championshipId: {
      type: Schema.Types.ObjectId,
      ref: "Championship",
      required: true,
    },
    rankingMode: {
      type: String,
      enum: Object.values(RankingMode),
      required: true,
    },
    rosterSize: { type: Number, required: true, min: 1 },
    startersPerGameweek: { type: Number, required: true, min: 1 },
    initialBudget: { type: Number, required: true, min: 0 },
    marketEnabled: { type: Boolean, default: false },
    status: {
      type: String,
      enum: Object.values(LeagueStatus),
      default: LeagueStatus.OPEN,
    },
    entryFee: { type: Number },
    prize1st: { type: String },
    prize2nd: { type: String },
    prize3rd: { type: String },
    inviteCode: { type: String, sparse: true, unique: true },
  },
  { timestamps: true },
);

LeagueSchema.index({ type: 1, status: 1 });
LeagueSchema.index({ championshipId: 1 });
LeagueSchema.index({ isOfficial: 1 });

export const League = mongoose.model<ILeague>("League", LeagueSchema);

export interface ILeagueMembership extends Document {
  leagueId: Types.ObjectId;
  userId: Types.ObjectId;
  enrolledAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const LeagueMembershipSchema = new Schema<ILeagueMembership>(
  {
    leagueId: {
      type: Schema.Types.ObjectId,
      ref: "League",
      required: true,
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    enrolledAt: { type: Date, required: true, default: Date.now },
  },
  { timestamps: true },
);

LeagueMembershipSchema.index({ leagueId: 1, userId: 1 }, { unique: true });
LeagueMembershipSchema.index({ userId: 1 });

export const LeagueMembership = mongoose.model<ILeagueMembership>(
  "LeagueMembership",
  LeagueMembershipSchema,
);

export interface IFantasyTeam extends Document {
  leagueId: Types.ObjectId;
  userId: Types.ObjectId;
  name: string;
  fantacoinsRemaining: number;
  totalPoints: number;
  createdAt: Date;
  updatedAt: Date;
}

const FantasyTeamSchema = new Schema<IFantasyTeam>(
  {
    leagueId: {
      type: Schema.Types.ObjectId,
      ref: "League",
      required: true,
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    name: { type: String, required: true, trim: true },
    fantacoinsRemaining: { type: Number, required: true, min: 0 },
    totalPoints: { type: Number, default: 0 },
  },
  { timestamps: true },
);

FantasyTeamSchema.index({ leagueId: 1, userId: 1 }, { unique: true });
FantasyTeamSchema.index({ leagueId: 1, totalPoints: -1 });

export const FantasyTeam = mongoose.model<IFantasyTeam>(
  "FantasyTeam",
  FantasyTeamSchema,
);

export interface IRoster extends Document {
  fantasyTeamId: Types.ObjectId;
  athleteId: Types.ObjectId;
  purchasePrice: number;
  currentValue: number;
  acquiredAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const RosterSchema = new Schema<IRoster>(
  {
    fantasyTeamId: {
      type: Schema.Types.ObjectId,
      ref: "FantasyTeam",
      required: true,
    },
    athleteId: {
      type: Schema.Types.ObjectId,
      ref: "Athlete",
      required: true,
    },
    purchasePrice: { type: Number, required: true, min: 0 },
    currentValue: { type: Number, required: true, min: 0 },
    acquiredAt: { type: Date, required: true, default: Date.now },
  },
  { timestamps: true },
);

RosterSchema.index({ fantasyTeamId: 1, athleteId: 1 }, { unique: true });
RosterSchema.index({ fantasyTeamId: 1 });

export const Roster = mongoose.model<IRoster>("Roster", RosterSchema);

export interface ILineup extends Document {
  fantasyTeamId: Types.ObjectId;
  tournamentId: Types.ObjectId;
  isLocked: boolean;
  autoGenerated: boolean;
  lockedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const LineupSchema = new Schema<ILineup>(
  {
    fantasyTeamId: {
      type: Schema.Types.ObjectId,
      ref: "FantasyTeam",
      required: true,
    },
    tournamentId: {
      type: Schema.Types.ObjectId,
      ref: "Tournament",
      required: true,
    },
    isLocked: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: false },
    lockedAt: { type: Date },
  },
  { timestamps: true },
);

LineupSchema.index({ fantasyTeamId: 1, tournamentId: 1 }, { unique: true });
LineupSchema.index({ tournamentId: 1, isLocked: 1 });

export const Lineup = mongoose.model<ILineup>("Lineup", LineupSchema);

export interface ILineupSlot extends Document {
  lineupId: Types.ObjectId;
  athleteId: Types.ObjectId;
  role: LineupRole;
  benchOrder?: number;
  substitutedIn: boolean;
  pointsScored: number;
  createdAt: Date;
  updatedAt: Date;
}

const LineupSlotSchema = new Schema<ILineupSlot>(
  {
    lineupId: {
      type: Schema.Types.ObjectId,
      ref: "Lineup",
      required: true,
    },
    athleteId: {
      type: Schema.Types.ObjectId,
      ref: "Athlete",
      required: true,
    },
    role: {
      type: String,
      enum: Object.values(LineupRole),
      required: true,
    },
    benchOrder: { type: Number },
    substitutedIn: { type: Boolean, default: false },
    pointsScored: { type: Number, default: 0 },
  },
  { timestamps: true },
);

LineupSlotSchema.index({ lineupId: 1, athleteId: 1 }, { unique: true });
LineupSlotSchema.index({ lineupId: 1, role: 1 });

export const LineupSlot = mongoose.model<ILineupSlot>(
  "LineupSlot",
  LineupSlotSchema,
);

export interface IGameweekStanding extends Document {
  leagueId: Types.ObjectId;
  fantasyTeamId: Types.ObjectId;
  tournamentId: Types.ObjectId;
  gameweekPoints: number;
  cumulativePoints: number;
  rank: number;
  createdAt: Date;
  updatedAt: Date;
}

const GameweekStandingSchema = new Schema<IGameweekStanding>(
  {
    leagueId: {
      type: Schema.Types.ObjectId,
      ref: "League",
      required: true,
    },
    fantasyTeamId: {
      type: Schema.Types.ObjectId,
      ref: "FantasyTeam",
      required: true,
    },
    tournamentId: {
      type: Schema.Types.ObjectId,
      ref: "Tournament",
      required: true,
    },
    gameweekPoints: { type: Number, default: 0 },
    cumulativePoints: { type: Number, default: 0 },
    rank: { type: Number, default: 0 },
  },
  { timestamps: true },
);

GameweekStandingSchema.index(
  { leagueId: 1, tournamentId: 1, fantasyTeamId: 1 },
  { unique: true },
);
GameweekStandingSchema.index({ leagueId: 1, tournamentId: 1, rank: 1 });

export const GameweekStanding = mongoose.model<IGameweekStanding>(
  "GameweekStanding",
  GameweekStandingSchema,
);
